apiVersion: v1
kind: Service
metadata:
  name: wbcam-service
  label:
    app: stx-webcam
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 33123
    targetPort: 8081
    nodePort: 30213
  selector:
    app: stx-webcam
    release: {{ .Release.Name }}
